bde_platform_homepage:
    path:     /
    defaults: { _controller: BDEPlatformBundle:Bde:index }

bde_admin_carousel:
    path:     /admin/carousel
    defaults: { _controller: BDEPlatformBundle:Bde:carousel }