bde_platform_homepage:
    path:     /
    defaults: { _controller: BDEPlatformBundle:Bde:index }

bde_admin_carousel:
    path:     /admin/carousel
    defaults: { _controller: BDEPlatformBundle:Bde:carousel }

bde_admin_edit_carousel:
    path: /admin/carousel/edit/{id}
    defaults: { _controller: BDEPlatformBundle:Bde:edit }
    requirements:
      id: \d+

bde_view_association:
    path: /associations
    defaults: { _controller: BDEPlatformBundle:Bde:associations }

bde_view_association_detail:
    path: /associations/view/{id}
    defaults: { _controller: BDEPlatformBundle:Bde:viewassociation }
    requirements:
      id: \d+

bde_test:
    path: /test
    defaults: { _controller: BDEPlatformBundle:Bde:test }

bde_boutique:
    path: /boutique
    defaults: { _controller: BDEPlatformBundle:Bde:boutique }