bde_platform_homepage:
    path:     /
    defaults: { _controller: BDEPlatformBundle:Bde:index }

bde_admin_carousel:
    path:     /admin/carousel
    defaults: { _controller: BDEPlatformBundle:Bde:carousel }

bde_admin_edit_carousel:
    path: /admin/carousel/edit/{id}
    defaults: { _controller: BDEPlatformBundle:Bde:edit }
    requirements:
      id: \d+

bde_view_association:
    path: /associations
    defaults: { _controller: BDEPlatformBundle:Bde:associations }

bde_view_association_detail:
    path: /associations/view/{id}
    defaults: { _controller: BDEPlatformBundle:Bde:viewassociation }
    requirements:
      id: \d+

bde_test:
    path: /test
    defaults: { _controller: BDEPlatformBundle:Bde:test }

bde_boutique:
    path: /boutique
    defaults: { _controller: BDEPlatformBundle:Bde:boutique }

bde_boutique_categorie:
    path: /boutique/{cat}
    defaults: { _controller: BDEPlatformBundle:Bde:boutiquecat }

bde_moncompte:
    path: /profil
    defaults: { _controller: BDEPlatformBundle:Bde:compte }

bde_ecole:
    path: /ecole
    defaults: { _controller: BDEPlatformBundle:Bde:ecole }



bde_galerie:
    path: /galerie
    defaults: { _controller: BDEPlatformBundle:Bde:galerie }

bde_check_connexion:
    path: /check
    defaults: { _controller: BDEPlatformBundle:Bde:checkconnexion }

bde_add_panier:
    path: /boutique/add/addpanier
    defaults: { _controller: BDEPlatformBundle:Bde:addpanier }

bde_view_panier:
    path: /view/panier
    defaults: { _controller: BDEPlatformBundle:Bde:viewpanier }

bde_remote_panier:
    path: /boutique/remote/panier
    defaults: { _controller: BDEPlatformBundle:Bde:remoteitem }

bde_addcommande:
    path: /boutique/add/commande
    defaults: { _controller: BDEPlatformBundle:Bde:commande }

bde_evenement:
    path: /evenement
    defaults: { _controller: BDEPlatformBundle:Bde:evenement }
bde_evenement_view:
    path: /evenement/view/{id}
    defaults: { _controller: BDEPlatformBundle:Bde:evenementview }

bde_commentaire_activite:
    path: /evenement/comment/{id}
    defaults: { _controller: BDEPlatformBundle:Bde:commentactivite }

bde_inscription_activite:
    path: /evenement/inscription/{id}
    defaults: { _controller: BDEPlatformBundle:Bde:inscriptionactivite }

bde_like_activite:
    path: /evenement/like/{id}
    defaults: { _controller: BDEPlatformBundle:Bde:likeactivite }
