<?php

namespace BDE\PlatformBundle\Repository;

/**
 * AssociationRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
