<?php

namespace BDE\PlatformBundle\Repository;

/**
 * AssociationRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRoleRepository extends \Doctrine\ORM\EntityRepository
{
	public function findRoleAssociation($asso,$role)
	{
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.association = :asso')->andWhere('a.role = :role')->setParameter('asso',$asso)->setParameter('role',$role);
		return $qb->getQuery()->getResult();
	}
}
