<?php

namespace BDE\PlatformBundle\Repository;

/**
 * CommentaireActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
