<?php

namespace BDE\PlatformBundle\Repository;

/**
 * LikePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikePhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
