<?php

namespace BDE\PlatformBundle\Repository;

/**
 * LikeActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
