<?php

namespace BDE\PlatformBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

	public function findProduit($categ)
	{
		$qb = $this->createQueryBuilder('a')->leftJoin('a.categories', 'categ');
		$qb->where('categ.nom = :categorie')->setParameter('categorie',$categ);
		return $qb->getQuery()->getResult();
	}
}
